name: Deploy to EC2
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to EC2 by using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          if [ ! -d "/home/ubuntu/app" ]
          then
            git clone git@github.com:ivanscloud/cicd.git /home/ubuntu/app
          fi
          cd /home/ubuntu/app
          git pull origin master
          docker stop TugasApp
          docker rm TugasApp
          cd program
          docker build -t tugas-app:latest .
          docker run -d -e "HTTP_PORT=:80" -e "CONNECTION_STRING=root:12345@tcp(3.1.101.175:3306)/alta_db?charset=utf8mb4&parseTime=True&loc=Local" -p 80:80 --name TugasApp tugas-app:latest